application:
  htmlParser:
    filespath: C:\work\tradelog\src\test\resources
server:
  port: 8000

spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: data/create.sql

  datasource:
    url: jdbc:h2:file:C:/work/tradelog/data/db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false