application:
  htmlParser:
    filespath: data/
server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: data/db/create.sql

  datasource:
    url: jdbc:mysql://172.17.0.2:3306/mydb
    username: mysql
    password: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
