application:
  htmlParser:
    filespath: /data/backup/
server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/mydb
    username: mysql
    password: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
