application:
  htmlParser:
    filespath: data/
spring:
  jpa:
    show_sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: /home/misha/tradelog/data/create.sql
logging:
  level:
    org:
      hibernate:
        type: trace