application:
  htmlParser:
    filespath: /home/misha/IdeaProjects/tradelog/src/test/resources
spring:
  datasource:
    url: jdbc:h2:file:/home/misha/tradelog/data/db
  jpa:
    show_sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: /home/misha/tradelog/data/create.sql
logging:
  level:
    org:
      hibernate:
        type: trace